Ultranet/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views


from account import views as account_views
from nomad import views as nomad_views
from blog.views import feed_view
from feedback import views as feedback_views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', nomad_views.HomeView.as_view(), name="home"),
    path('about/', nomad_views.AboutView.as_view(), name="about_page"),
    path('get_in_touch/', nomad_views.ContactView.as_view(), name="contact_page"),
    path('legal-docs/', nomad_views.LegalDocsView.as_view(), name="legal_docs_page"),

    path('register/', account_views.register_view, name="register"),
    path('login/', account_views.login_view, name="login"),
    path('logout/', account_views.logout_view, name="logout"),
    path('account/', include('account.urls', namespace="account")),
    path('friend/', include('friend.urls', namespace="friend")),
    path('', include('main_asgi.urls', namespace="main_asgi")),
    path('feedback/', include('feedback.urls', namespace="feedback")),
    path('notifications/', include('main_asgi.chat_urls', namespace="notifications")),
    path('blog/', include('blog.urls', namespace="blog")),
    path('', include('nomad.urls', namespace="nomad")),
    
    path('report/', feedback_views.create_report_view, name="report"),
    path('lobby/', feed_view, name="feed"),
    
    path('chat/', include('main_asgi.chat_urls', namespace="chat")),
    path('notifications/', include('main_asgi.notifications_urls', namespace="notification")),

    path('password-reset/', auth_views.PasswordResetView.as_view(template_name="account/password-reset/reset.html"), name="password_reset"),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='account/password-reset/reset_done.html'), name="password_reset_done"),
    path('password-reset/complete/', auth_views.PasswordResetCompleteView.as_view(template_name='account/password-reset/reset_complete.html'), name="password_reset_complete"),    
    path('password-reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="account/password-reset/reset_confirm.html"), name='password_reset_confirm'),

    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='account/password-reset/change_done.html'),name='password_change_done'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='account/password-reset/change.html'),name='password_change'),

    path('server_error/', nomad_views.server_error_view, name="500"),
    path('page_not_found/', nomad_views.page_not_found_view, name="404"),
    path('bad_request', nomad_views.bad_request_view, name="400"),
    path('permision_denied/', nomad_views.perm_denied_view, name="403"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = nomad_views.page_not_found_view
handler500 = nomad_views.server_error_view
handler403 = nomad_views.perm_denied_view
handler400 = nomad_views.bad_request_view

account/urls.py
from django.urls import path

from . import views

app_name="account"

urlpatterns = [
	path('redirect/', views.redirect_view, name="redirect"),
	path('update_profile/', views.update_profile_view, name="update_profile"),
	path('settings/<str:page>/', views.settings_view, name="settings"),
	path('details/<str:subject_username>/', views.details_view, name="details"),
	path('delete/', views.delete_account_view, name="delete"),
	path('<user_id>/edit/cropImage/', views.crop_image_view, name="crop_image"),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include


from . import views

from account import views as account_views

from .views import (
	# CRUD
	create_content_view,
	create_comment_view,

	update_content_view,
	update_comment_view,

	delete_content_view,
	delete_comment_view,

	feed_view,
	content_view,
	select_view,
	interact_view,
	)

app_name="blog"

urlpatterns = [

	path('create/<str:content_type>/', create_content_view, name="create_content"),
	path('<int:content_id>/', content_view, name="content"),
	path('poll/select/<int:value_id>/', select_view, name="select"),
	path('<int:content_id>/update/', update_content_view, name="update_content"),
	path('<int:content_id>/delete/', delete_content_view, name="delete_content"),

	path('<int:content_id>/<int:reply>/comments/create/', create_comment_view, name="create_comment"),
	path('content/<comment_id>/edit/', update_comment_view, name="update_comment"),
	path('content/<comment_id>/delete/', delete_comment_view, name="delete_comment"),

	path('interact/', interact_view, name="interact"),
]

friend/urls.py
from django.urls import path
from .views import (
    friend_requests_view,
    send_friend_request_view,
    accept_friend_request_view,
    decline_friend_request_view,
    unfriend_view,
    cancel_friend_request_view,
    friend_list_view,
    accounts_view,
)

app_name = "friend"

urlpatterns = [
    path('friend_request/', send_friend_request_view, name="send"),
    path('friend_requests/<user_id>/', friend_requests_view, name="friend_requests"),
    path('accept_friend_request/<friend_request_id>/', accept_friend_request_view, name="accept"),
    path('remove/', unfriend_view, name="unfriend"),
    path('decline_friend_request/<friend_request_id>/', decline_friend_request_view, name="decline"),
    path('cancel_friend_request/', cancel_friend_request_view, name='cancel'),
    path('friend_list_view/<user_id>/', friend_list_view, name="friend_list"),
    path('mingle/<int:user_id>/', accounts_view, name="accounts"),
]

friend/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
import json
from account.models import Account
from .models import FriendRequest, FriendList
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from friend.friend_request_status import FriendRequestStatus
from friend.utils import get_friend_request_or_false
from main_asgi.models import PublicChatRoom, Notification


# Create your views here.
@login_required(login_url="login")
def friend_requests_view(request, *args, **kwargs):
	context = {}
	auth_user = request.user
	
	if auth_user.is_authenticated:
		friend_requests = FriendRequest.objects.filter(receiver=auth_user).distinct('sender')
		context['friend_requests'] = friend_requests
	else:
		redirect("login")

	context["con_general"] = True
	return render(request ,"friend/friend_requests.html", context)

@login_required(login_url="login")
def send_friend_request_view(request, *args, **kwargs):
	print("[+] Send friend request view running")
	auth_user = request.user
	payload = {}
	
	if auth_user.is_authenticated and request.method == "POST":
		receiver_id = request.POST.get("receiver_user_id")
		if receiver_id:
			receiver = Account.objects.get(pk=receiver_id)
			try:
				# Get any friend requests (active and not-active)
				friend_requests = FriendRequest.objects.filter(sender=auth_user, receiver=receiver)
				# find if any of them are active (pending)
				try:
					for request in friend_requests:
						if request:
							friend_request.delete()

					# If none are active create a new friend request
					friend_request = FriendRequest(sender=auth_user, receiver=receiver)
					friend_request.save()
					payload['response'] = "[+] Friend request sent."
					payload['receiver'] = receiver.username
					print("request sent")
				except Exception as e:
					payload['response'] = "[-] An error occured , try again"
			except FriendRequest.DoesNotExist:
				# There are no friend requests so create one.
				friend_request = FriendRequest(sender=auth_user, receiver=receiver)
				friend_request.save()
				payload['response'] = "[+] Friend request sent."
				print("request sent")

			if payload['response'] == None:
				payload['response'] = "[-] Something went wrong."
		else:
			payload['response'] = "[-] Unable to sent the friend request."
	else:
		return redirect("login")

	return HttpResponse(json.dumps(payload), content_type="application/json")

@login_required(login_url="login")
def accept_friend_request_view(request, *args, **kwargs):
	auth_user = request.user
	payload = {}
	
	if auth_user.is_authenticated and request.method == "GET":
		#	Get the friend request id from the url
		friend_request_id = kwargs.get("friend_request_id")

		if friend_request_id:
			#	Get the friend request from the database
			friend_requests = FriendRequest.objects.filter(pk=friend_request_id)
			if len(friend_requests)==0:
				payload['response']=="reload"
			elif len(friend_requests)>=1:
				friend_request=friend_requests[0]
				if friend_request.receiver == auth_user:
					if friend_request:
						#	Found it and we are accepting it
						#	We built the accept function in the model
						friend_request.accept()
						for fr in FriendRequest.objects.filter(sender=friend_request.sender, receiver=auth_user):
							fr.delete()

						# Update the allowed_friends field in their public chatrooms
						for room in list(PublicChatRoom.objects.filter(admin=friend_request.receiver)):
							if room.accessibility == "Friends":
								pub_room.allowed_friends.add(friend_request.sender)
								pub_room.save()

						for room in list(PublicChatRoom.objects.filter(admin=friend_request.sender)):
							if room.accessibility == "Friends":
								pub_room.allowed_friends.add(friend_request.receiver)
								pub_room.save()

						payload['response'] = "[+] Friend request accepted"
					else:
						payload['response'] = "[-] Something went wrong"
				else:
					payload['response'] = "[-]hat is not your request to accept"
		else:
			payload['response'] = "[-] Unable to accept that reqeust"
	elif not auth_user.is_authenticated:
		return redirect("login")
	else:
		payload['response'] = "You must be authenticated to accept a friend request"
	return HttpResponse(json.dumps(payload), content_type="application/json")

@login_required(login_url="login")
def decline_friend_request_view(request, *args, **kwargs):
	payload = {}
	auth_user = request.user
	
	if auth_user.is_authenticated:
		#	Get the friend request id from the url
		friend_request_id = kwargs.get("friend_request_id")
		if friend_request_id:
			#	Get the friend request from the database
			friend_requests = FriendRequest.objects.filter(pk=friend_request_id)
			if len(friend_requests)==0:
				payload['response']=="reload"
			elif len(friend_requests)>=1:
				friend_request=friend_requests[0]
				if friend_request.receiver == auth_user:
					if friend_request:
						#	Found it and we are accepting it
						#	We built the accept function in the model
						friend_request.decline()
						payload['response'] = "[+] Friend request declined"
					else:
						payload['response'] = "[-] Something went wrong"
				else:
					payload['response'] = "[-] That is not your request to decline"
		else:
			payload['response'] = "[-] Unable to decline that reqeust"
	else:
		payload["response"] = " "
		return redirect("login")
		
	return HttpResponse(json.dumps(payload), content_type="application/json")

@login_required(login_url="login")
def unfriend_view(request, *args, **kwargs):
	payload = {}
	auth_user = request.user
	
	if auth_user.is_authenticated and request.method == "POST":
		receiver_id = request.POST.get("receiver_user_id")
		if receiver_id:
			try:
				removee = Account.objects.get(pk=receiver_id)
				#	Our friend list
				friend_list = FriendList.objects.get(user=auth_user)
				#	The function was built in the models.py file
				friend_list.unfriend(removee)
				payload['response'] = "[+] Successfully removed that friend"
			except Exception as e:
				payload['response'] = "[-] Something went wrong"
				print(str(e))
		else:
			payload['response'] = "[-] An error occured, please try again"

	else:
		return redirect("login")

	return HttpResponse(json.dumps(payload), content_type="application/json")

@login_required(login_url="login")
def cancel_friend_request_view(request, *args, **kwargs):
	print("[+] Cancell friend request view running")
	payload = {}
	auth_user = request.user
	
	if auth_user.is_authenticated and request.method == "POST":
		#	Get my user id
		receiver_id = request.POST.get("receiver_user_id")
		
		if receiver_id:
			#	Get the receiver of the friend request
			receiver = Account.objects.get(pk=receiver_id)
			try:
				#	Get all friend requests that are active between me and the receiver [ 1 ]
				friend_requests = FriendRequest.objects.filter(sender=auth_user, receiver=receiver)

			except Exception as e:
				payload['response'] = "[-] Nothing to cancel"

			#	If there are more than one friend requests cancell them all
			if len(friend_requests) > 1:
				for request in friend_requests:
					request.cancel()
				payload['response'] = "[+] Friend request cancelled"
			#	Cancell the single friend request
			elif len(friend_requests) == 1:
				friend_requests.first().cancel()
				payload['response'] = "[+] Friend request cancelled"
		else:
			payload['response'] = "[-] Unable to cancel that reqeust"
	else:
		return redirect("login")
		
	return HttpResponse(json.dumps(payload), content_type="application/json")

@login_required(login_url="login")
def friend_list_view(request, *args, **kwargs):
	context = {}
	auth_user = request.user
	if auth_user.is_authenticated:
		auth_user_account = Account.objects.get(id=int(auth_user.id))
		subject_id = kwargs.get("user_id")
		if subject_id:
			try:
				subject_account = Account.objects.get(pk=subject_id)
				# Change this_user in the template
				context['subject'] = subject_account
				friend_list = FriendList.objects.get(user=subject_account)

			except FriendList.DoesNotExist:
				friend_list = FriendList.objects.create(user=subject_account)
				friend_list.save()
			
			if subject_account == auth_user_account or (subject_account.settings.visibility_friend_list == "Anyone") or (subject_account.settings.visibility_friend_list == "Friends" and auth_user_account in friend_list.friends.all()):
				friends = [] # [(friend1, True), (friend2, False), ...]
				# get the authenticated users friend list
				# Checking if any of the subject's friends are my friends
				auth_user_friend_list = FriendList.objects.get(user=subject_account)
				for friend in friend_list.friends.all():
					friends.append((friend, friend in auth_user_account.friend_list.friends.all()))
				context['friends'] = friends
	else:		
		return redirect("login")
	context["con_general"] = True
	return render(request, "friend/friend_list.html", context)		

@login_required(login_url="login")
def accounts_view(request, *args, **kwargs):
	context = {}
	auth_user = request.user
	if auth_user.is_authenticated:
		auth_user_id = kwargs.get("user_id")
		if auth_user_id:
			try:
				auth_user_account = Account.objects.get(id=auth_user_id)
			except:
				return redirect("error:does_not_exist", origin=origin)

			accounts = []
			try:
				# Filters needed
				accounts = list(Account.objects.all())
				accounts.remove(auth_user_account)
			except:
				return redirect("error:does_not_exist", origin=origin)

			try:
				auth_user_friend_list = FriendList.objects.get(user=auth_user_account)
			except FriendList.DoesNotExist:
				auth_user_friend_list = FriendList.objects.create(user=auth_user_account)
				auth_user_friend_list.save()

			accounts_filtered = []
			for account in accounts:
				if auth_user_friend_list.is_mutual_friend(account):
					pass
				else:

					# CASE1: Request has been sent from THEM to YOU: FriendRequestStatus.THEM_SENT_TO_YOU

friend/templates/friend/accept_jquery.html
<script type="text/javascript">
    function acceptFriendRequest(friend_request_id) {
        var url = "{% url 'friend:accept' friend_request_id=525613164613352031 %}".replace("525613164613352031", friend_request_id)
        
        $.ajax({
            type: "GET",
            dataType: "json",
            url: url,
            timeout: 5000,
            success: function (data) {
                location.reload()
            },
            error: function (data) {
                console.log("[-] Something went wrong")
            },
            complete: function (data) {
                uiUpdateFunction()
            },            
        })
    }
</script>

friend/templates/friend/cancel_jquery.html
<script type="text/javascript">
    function cancelFriendRequest(id) {  
        payload = {
            "csrfmiddlewaretoken": "{{ csrf_token }}",
            "receiver_user_id": id, 
        }
        $.ajax({
            type: "POST",
            data: payload,
            url: "{% url 'friend:cancel' %}",
            timeout: 5000,  
            success: function(data) {
                location.reload()
            },
            error: function(data) {
                console.error("[-] An error occured")
            },
            complete: function(data) {
                location.reload()
            },
        })
    }

</script>

friend/templates/friend/decline_jquery.html
<script type="text/javascript">
    function declineFriendRequest(friend_request_id) {
        var url = "{% url 'friend:decline' friend_request_id=525613164613352032 %}".replace("525613164613352032", friend_request_id)
        $.ajax({
            type: "GET",
            dataType: "json",
            url: url,
            timeout: 5000,
            success: function (data) {
                location.reload()
            },
            error: function (data) {
                console.log("Something went wrong")
            },
            complete: function (data) {
                uiUpdateFunction()
            },            
        })
    }
</script>

friend/templates/friend/friend_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Friend list
{% endblock title %}

{% block content %}
<style type="text/css">
	.profile-image{
		max-height: 60px;
		max-width: 60px;
	}
	.profile-image{
		border-radius: 12px;
	}
	.card{
		border-radius: 12px;
	}
	.friends-text{
		color: #000;
		font-weight: 500;
	}
	.friends-text-container{
		border: 1px solid #cccccc;
		border-radius: 12px;
	}
	.friends-btn:hover {
		background-color: #bfbfbf;
		border-color: #bfbfbf;
	}
	.dropdown-toggle::after { 
		content: none; 
	}
	.profile-link{
		color: #000;
	}
	.checkmark-icon{
		color: green;
	}
	.cancel-icon{
		color: red;
	}
</style>

<div class="container">
	<div class="card p-2">
		{% if friends %}
			<div class="d-flex flex-row flex-wrap">
			{% for friend in friends %}
				<div class="card flex-row flex-grow-1 mx-2 my-2 align-items-center">
					<a class="profile-link" href="{% url 'account:details' subject_username=friend.0.username %}">
						<div class="card-image m-2">
							<img class="card-image profile-image" src="{{ friend.0.profile_image.url }}" alt="">
						</div>
					</a>
					
					<div class="card-center px-2">
						<a class="profile-link" href="{% url 'account:details' subject_username=friend.0.username %}">
							<h4 class="card-title">{{friend.0.username|truncatechars:50}}</h4>
						</a>
						
					</div>
					
					<div class="d-flex flex-row card-right flex-grow-1 justify-content-end mx-2">
						{% if friend.1 %}
							<div class="d-flex flex-row">
								<small class="tillium text-white btn btn-secondary">
									Friends 
								</small>
							</div>	
						{% elif friend.0 == request.user %}
							<div class="d-flex flex-row">
								<small class="tillium text-white btn btn-secondary">
									You 
								</small>
							</div>
						{% endif %}
					</div>
				</div>
				{% if forloop.counter|divisibleby:2 %}
					</div><div class="d-flex flex-row flex-wrap">
				{% endif %}
				
			{% endfor %}
			
		{% else %} <!-- If no friends -->
			<div class="d-flex flex-row flex-grow-1 justify-content-center align-items-center p-4">
				<p>No friends :(</p>
			</div>
		{% endif %}

    </div>	
</div>

{% endblock content %}

friend/templates/friend/friend_requests.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Post search
{% endblock %}

{% block content %}
<style type="text/css">
	.profile-image{
		max-height: 60px;
		max-width: 60px;
	}
	.profile-image{
		border-radius: 12px;
	}
	.card{
		border-radius: 12px;
	}
	.dropdown-toggle::after { 
		content: none; 
	}
	.profile-link{
		color: #000;
	}
	.material-icons{
		font-size: 30px;
	}
	.material-icons:hover{
		cursor: pointer;
	}
	.confirm-friend-request{
		color: green;
	}
	.confirm-friend-request:hover {
		opacity: 0.3;
	}
	.decline-friend-request:hover {
		opacity: 0.3;
	}
	.decline-friend-request{
		color: red;
	}
</style>

<div class="container mt-3">
	<div class="card p-2">
		{% if friend_requests %}
			<div class="d-flex flex-row flex-wrap">
			{% for friend_request in friend_requests %}
				<div class="card flex-row flex-grow-1 p-2 mx-2 my-2 align-items-center">
					<a class="profile-link" href="{% url 'account:details' subject_username=friend_request.receiver.username %}">
						<div class="card-image m-2">
							<img class="card-image profile-image" src="{{ friend_request.sender.profile_image.url }}" alt="">
						</div>
					</a>
					<a class="profile-link flex-grow-1" href="{% url 'account:details' subject_username=friend_request.sender.username %}">
						<div class="card-center px-2">
							<h4 class="card-title">{{friend_request.sender.username}}</h4>
						</div>
					</a>
					<p class="flex-shrink-1">
						<button style="color: green;" class="mt-4 btn" type="button" id="id_confirm_{{friend_request.sender.id}}" class="confirm-friend-request material-icons p-1" onclick='triggerAcceptFriendRequest("{{friend_request.id}}","{{ friend_request.receiver.username }}")'><i class="fa fa-check-circle fa-2x"></i></button>
				  		<button style="color: red;" type="button" class="mt-4 btn" id="id_cancel_{{friend_request.sender.id}}"class="decline-friend-request material-icons p-1" onclick='triggerDeclineFriendRequest("{{friend_request.id}}")'><i class="fa fa-times-circle fa-2x"></i></button>
			  		</p>
					  
				{% if forloop.counter|divisibleby:2 %}
				</div><div class="d-flex flex-row flex-wrap">
				{% endif %}
			
			{% endfor %}	
		{% else %}

				<!-- If no friends -->
				<div class="d-flex flex-row flex-grow-1 justify-content-center align-items-center p-4">
					<p>No results</p>
				</div>
		{% endif %}
	</div>
</div>


<script type="text/javascript">

	function onFriendRequestAccepted(){
		location.reload();
	}

	function onFriendRequestDeclined(){
		location.reload();
	}

	function triggerAcceptFriendRequest(friend_request_id, username){
		acceptFriendRequest(friend_request_id, onFriendRequestAccepted, username)
	}

	function triggerDeclineFriendRequest(friend_request_id){
		declineFriendRequest(friend_request_id, onFriendRequestDeclined)
	}
</script>

{% include 'friend/accept_jquery.html' %}
{% include 'friend/decline_jquery.html' %}

{% endblock content %}

friend/templates/friend/send_jquery.html
<script type="text/javascript">
	function sendFriendRequest(id){
		payload = {
			"csrfmiddlewaretoken": "{{ csrf_token }}",
			"receiver_user_id": id,
		}
		$.ajax({
			type: 'POST',
			dataType: "json",
			url: "{% url 'friend:send' %}",
			timeout: 5000,
			data: payload,
			success: function(data) {
				//
			},
			error: function(data) {
				console.log("[-] An error occured")
			},
			complete: function(data){
				location.reload()
			}
		});
	}
</script>

friend/templates/friend/unfriend_jquery.html
<script type="text/javascript">
    function removeFriend(id) {
        payload = {
            // This is how you include the csrf token in ajax
            // You have to do this everytime you make a post request
            "csrfmiddlewaretoken": "{{ csrf_token }}",
            "receiver_user_id": id,
        },
        $.ajax ({
            type: "POST", 
            dataType: "json",
            timeout: 5000,
            url: "{% url 'friend:unfriend' %}",
            data: payload,
            success: function (data) {
                //
            },
            error: function (data) {
                console.error("[-] Something went wrong" )
            },
            complete: function (data) {
                location.reload()
            },
        })
    }
</script>