Ultranet/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views


from account import views as account_views
from nomad import views as nomad_views
from blog.views import feed_view
from feedback import views as feedback_views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', nomad_views.HomeView.as_view(), name="home"),
    path('about/', nomad_views.AboutView.as_view(), name="about_page"),
    path('get_in_touch/', nomad_views.ContactView.as_view(), name="contact_page"),
    path('legal-docs/', nomad_views.LegalDocsView.as_view(), name="legal_docs_page"),

    path('register/', account_views.register_view, name="register"),
    path('login/', account_views.login_view, name="login"),
    path('logout/', account_views.logout_view, name="logout"),
    path('account/', include('account.urls', namespace="account")),
    path('friend/', include('friend.urls', namespace="friend")),
    path('', include('main_asgi.urls', namespace="main_asgi")),
    path('feedback/', include('feedback.urls', namespace="feedback")),
    path('notifications/', include('main_asgi.chat_urls', namespace="notifications")),
    path('blog/', include('blog.urls', namespace="blog")),
    path('', include('nomad.urls', namespace="nomad")),
    
    path('report/', feedback_views.create_report_view, name="report"),
    path('lobby/', feed_view, name="feed"),
    
    path('chat/', include('main_asgi.chat_urls', namespace="chat")),
    path('notifications/', include('main_asgi.notifications_urls', namespace="notification")),

    path('password-reset/', auth_views.PasswordResetView.as_view(template_name="account/password-reset/reset.html"), name="password_reset"),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='account/password-reset/reset_done.html'), name="password_reset_done"),
    path('password-reset/complete/', auth_views.PasswordResetCompleteView.as_view(template_name='account/password-reset/reset_complete.html'), name="password_reset_complete"),    
    path('password-reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="account/password-reset/reset_confirm.html"), name='password_reset_confirm'),

    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='account/password-reset/change_done.html'),name='password_change_done'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='account/password-reset/change.html'),name='password_change'),

    path('server_error/', nomad_views.server_error_view, name="500"),
    path('page_not_found/', nomad_views.page_not_found_view, name="404"),
    path('bad_request', nomad_views.bad_request_view, name="400"),
    path('permision_denied/', nomad_views.perm_denied_view, name="403"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = nomad_views.page_not_found_view
handler500 = nomad_views.server_error_view
handler403 = nomad_views.perm_denied_view
handler400 = nomad_views.bad_request_view

account/urls.py
from django.urls import path

from . import views

app_name="account"

urlpatterns = [
	path('redirect/', views.redirect_view, name="redirect"),
	path('update_profile/', views.update_profile_view, name="update_profile"),
	path('settings/<str:page>/', views.settings_view, name="settings"),
	path('details/<str:subject_username>/', views.details_view, name="details"),
	path('delete/', views.delete_account_view, name="delete"),
	path('<user_id>/edit/cropImage/', views.crop_image_view, name="crop_image"),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include


from . import views

from account import views as account_views

from .views import (
	# CRUD
	create_content_view,
	create_comment_view,

	update_content_view,
	update_comment_view,

	delete_content_view,
	delete_comment_view,

	feed_view,
	content_view,
	select_view,
	interact_view,
	)

app_name="blog"

urlpatterns = [

	path('create/<str:content_type>/', create_content_view, name="create_content"),
	path('<int:content_id>/', content_view, name="content"),
	path('poll/select/<int:value_id>/', select_view, name="select"),
	path('<int:content_id>/update/', update_content_view, name="update_content"),
	path('<int:content_id>/delete/', delete_content_view, name="delete_content"),

	path('<int:content_id>/<int:reply>/comments/create/', create_comment_view, name="create_comment"),
	path('content/<comment_id>/edit/', update_comment_view, name="update_comment"),
	path('content/<comment_id>/delete/', delete_comment_view, name="delete_comment"),

	path('interact/', interact_view, name="interact"),
]

templates/snippets/footer.html
<footer class="app-footer border-top">
    <div class="py-2 mt-auto container px-3">
        <div class="row py-1">

            <div class="col-12">
                <div class="d-flex flex-row">
	                <div class="flex-grow-1">
						<small class="copyright text-light">© Ultranet 2022</small>
	                </div>
	                <div class="flex-shrink-1 pt-2">
	                    <a class="text-light" href="#!"><i class="fab fa-github fa-lg"></i></a>
	                    <span class="text-white mx-1">·</span>
	                    <a class="text-light" href="#!"><i class="fab fa-instagram fa-lg"></i></a>
	                    <span class="text-white mx-1">·</span>
	                    <a class="h6 tillium text-light" href="#!"><i class="fab fa-facebook fa-lg"></i></a>   
	                </div>
				</div>
            </div>
            <div class="col-12 py-0 my-0 text-start">

				<small class="copyright text-light">Designed by <a class="app-link text-light" href="http://themes.3rdwavemedia.com" target="_blank">Xiaoying Riley</a></small>

            </div>        



        </div>
    </div>

</footer>

templates/snippets/header.html
{% load static %}
<header class="app-header fixed-top">	   	            
    <div class="app-header-inner">  
        <div class="container-fluid py-2">
	        <div class="app-header-content"> 
	            <div class="row justify-content-between align-items-center">
		        
			    <div class="col-auto">
				    <a id="sidepanel-toggler" class="sidepanel-toggler d-inline-block d-xl-none" href="#">
					    <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 30 30" role="img"><title>Menu</title><path stroke="currentColor" stroke-linecap="round" stroke-miterlimit="10" stroke-width="2" d="M4 7h22M4 15h22M4 23h22"></path></svg>
				    </a>
			    </div><!--//col-->

			    {% if request.user.is_authenticated %}
	            <div class="search-mobile-trigger d-sm-none col">
		            <i class="search-mobile-trigger-icon fas fa-search"></i>
		        </div><!--//col-->
	            <div class="app-search-box col">
	                <form class="app-search-form">   
						<input type="text" placeholder="Search..." name="search" class="form-control search-input">
						<button type="submit" class="btn search-btn btn-primary" value="Search"><i class="fas fa-search"></i></button> 
			        </form>
	            </div><!--//app-search-box-->

	            
	            <div class="app-utilities col-auto">
		            <div class="app-utility-item app-notifications-dropdown dropdown">    
			            <a class="dropdown-toggle no-toggle-arrow" id="notifications-dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false" title="Notifications">
				            <!--//Bootstrap Icons: https://icons.getbootstrap.com/ -->
				            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-bell icon" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
							  <path d="M8 16a2 2 0 0 0 2-2H6a2 2 0 0 0 2 2z"/>
							  <path fill-rule="evenodd" d="M8 1.918l-.797.161A4.002 4.002 0 0 0 4 6c0 .628-.134 2.197-.459 3.742-.16.767-.376 1.566-.663 2.258h10.244c-.287-.692-.502-1.49-.663-2.258C12.134 8.197 12 6.628 12 6a4.002 4.002 0 0 0-3.203-3.92L8 1.917zM14.22 12c.223.447.481.801.78 1H1c.299-.199.557-.553.78-1C2.68 10.2 3 6.88 3 6c0-2.42 1.72-4.44 4.005-4.901a1 1 0 1 1 1.99 0A5.002 5.002 0 0 1 13 6c0 .88.32 4.2 1.22 6z"/>
							</svg>
				            <span class="icon-badge" id="notification_count">0</span>
				        </a><!--//dropdown-toggle-->
				        
				        <div class="dropdown-menu p-0" aria-labelledby="notifications-dropdown-toggle">
				            <div class="dropdown-menu-header p-3">
					            <h5 class="dropdown-menu-title mb-0">Notifications</h5>
					        </div><!--//dropdown-menu-title-->
					        <div class="dropdown-menu-content">
						       <div class="item p-3">
							        <div class="row gx-2 justify-content-between align-items-center">
								        <div class="col-auto">
									       <img class="profile-image" src="assets/images/profiles/profile-1.png" alt="">
								        </div><!--//col-->
								        <div class="col">
									        <div class="info"> 
										        <div class="desc">Amy shared a file with you. Lorem ipsum dolor sit amet, consectetur adipiscing elit. </div>
										        <div class="meta"> 2 hrs ago</div>
									        </div>
								        </div><!--//col--> 
							        </div><!--//row-->
							        <a class="link-mask" href="notifications.html"></a>
						       </div><!--//item-->
						       <div class="item p-3">
							        <div class="row gx-2 justify-content-between align-items-center">
								        <div class="col-auto">
									        <div class="app-icon-holder">
										        
									        </div>
								        </div><!--//col-->
								        <div class="col">
									        <div class="info"> 
										        <div class="desc">You have a new invoice. Proin venenatis interdum est.</div>
										        <div class="meta"> 1 day ago</div>
									        </div>
								        </div><!--//col-->
							        </div><!--//row-->
							        <a class="link-mask" href="notifications.html"></a>
						       </div><!--//item-->
						       <div class="item p-3">
							        <div class="row gx-2 justify-content-between align-items-center">
								        <div class="col-auto">
									        <div class="app-icon-holder icon-holder-mono">
										        
									        </div>
								        </div><!--//col-->
								        <div class="col">
									        <div class="info"> 
										        <div class="desc">Your report is ready. Proin venenatis interdum est.</div>
										        <div class="meta"> 3 days ago</div>
									        </div>
								        </div><!--//col-->
							        </div><!--//row-->
							        <a class="link-mask" href="notifications.html"></a>
						       </div><!--//item-->
						       <div class="item p-3">
							        <div class="row gx-2 justify-content-between align-items-center">
								        <div class="col-auto">
									       <img class="profile-image" src="assets/images/profiles/profile-2.png" alt="">
								        </div><!--//col-->
								        <div class="col">
									        <div class="info"> 
										        <div class="desc">James sent you a new message.</div>
										        <div class="meta"> 7 days ago</div>
									        </div>
								        </div><!--//col--> 
							        </div><!--//row-->
							        <a class="link-mask" href="notifications.html"></a>
						       </div><!--//item-->
					        </div><!--//dropdown-menu-content-->
					        
					        <div class="dropdown-menu-footer p-2 text-center">
						        <a href="notifications.html">View all</a>
					        </div>
														
						</div><!--//dropdown-menu-->					        
			        </div><!--//app-utility-item-->
		            <div class="app-utility-item">
			            <a href="settings.html" title="Settings">
				            <!--//Bootstrap Icons: https://icons.getbootstrap.com/ -->
				            
				        </a>
				    </div><!--//app-utility-item-->
		            
		            <div class="app-utility-item app-user-dropdown dropdown">
			            <a class="dropdown-toggle" id="user-dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false"><img src="{{ request.user.profile_image.url }}" alt="user profile" class="rounded-circle"></a>
			            <ul class="dropdown-menu" aria-labelledby="user-dropdown-toggle">
							<li><a class="dropdown-item" href="{% url 'account:details' subject_username=request.user.username %}">Account</a></li>
							<li><a class="dropdown-item" href="{% url 'account:settings' page='main' %}">Settings</a></li>
							<li><hr class="dropdown-divider"></li>
							<li><a class="dropdown-item" href="{% url 'logout' %}">Log Out</a></li>
						</ul>
		            </div><!--//app-user-dropdown--> 
	            </div><!--//app-utilities-->
	            {% endif %}
	        </div><!--//row-->
            </div><!--//app-header-content-->
        </div><!--//container-fluid-->
    </div><!--//app-header-inner-->
    <div id="app-sidepanel" class="app-sidepanel"> 
        <div id="sidepanel-drop" class="sidepanel-drop"></div>
        <div class="sidepanel-inner d-flex flex-column">
	        <a href="#" id="sidepanel-close" class="sidepanel-close d-xl-none">&times;</a>
	        <div class="app-branding">
	            <a class="app-logo" href="index.html"><img class="logo-icon me-2" src="{% static 'logos/light.svg' %}" alt="logo"><span class="logo-text">ULTRANET</span></a>

	        </div><!--//app-branding-->  
	        
		    <nav id="app-nav-main" class="app-nav app-nav-main flex-grow-1">
			    <ul class="app-menu list-unstyled accordion" id="menu-accordion">
				    <li class="nav-item">
				        <!--//Bootstrap Icons: https://icons.getbootstrap.com/ -->
				        <a class="nav-link active" href="{% url 'home' %}">
					        <span class="nav-icon">
					        	<i class="fa fa-home fa-lg"></i>
					         </span>
	                         <span class="nav-link-text">Home</span>
				        </a><!--//nav-link-->
				    </li><!--//nav-item-->
				    
				    {% if request.user.is_authenticated %}
				    <li class="nav-item">
				        <!--//Bootstrap Icons: https://icons.getbootstrap.com/ -->
				        <a class="nav-link" href="{% url 'feed' %}">
					        <span class="nav-icon">
					        	<i class="fa fa-list-alt fa-lg"></i>
					         </span>
	                         <span class="nav-link-text">Feed</span>
				        </a><!--//nav-link-->
				    </li><!--//nav-item-->

				    <li class="nav-item has-submenu">
				        <!--//Bootstrap Icons: https://icons.getbootstrap.com/ -->
				        <a class="nav-link submenu-toggle" href="#" data-bs-toggle="collapse" data-bs-target="#submenu-1" aria-expanded="false" aria-controls="submenu-1">
					        <span class="nav-icon">
					        <!--//Bootstrap Icons: https://icons.getbootstrap.com/ -->
					        	<i class="fa fa-pencil-alt fa-lg"></i>
					         </span>
	                         <span class="nav-link-text">Create</span>
	                         <span class="submenu-arrow">
	                             
                             </span><!--//submenu-arrow-->
				        </a><!--//nav-link-->
				        <div id="submenu-1" class="collapse submenu submenu-1" data-bs-parent="#menu-accordion">
					        <ul class="submenu-list list-unstyled">
						        <li class="submenu-item"><a class="submenu-link" href="{% url 'blog:create_content' content_type='Post' %}">Post</a></li>
						        <li class="submenu-item"><a class="submenu-link" href="{% url 'blog:create_content' content_type='Poll' %}">Poll</a></li>
					        </ul>
				        </div>
				    </li><!--//nav-item-->
				    {% endif %}


			    </ul><!--//app-menu-->
		    </nav><!--//app-nav-->
		    <div class="app-sidepanel-footer">
			    <nav class="app-nav app-nav-footer">
				    <ul class="app-menu footer-menu list-unstyled">
				    	{% if request.user.is_authenticated %}
					    <li class="nav-item">
					        <!--//Bootstrap Icons: https://icons.getbootstrap.com/ -->
					        <a class="nav-link" href="{% url 'account:settings' page='main' %}">
						        <span class="nav-icon">
						           <i class="fa fa-cog fa-lg"></i> 
						        </span>
		                        <span class="nav-link-text">Settings</span>
					        </a><!--//nav-link-->
					    </li><!--//nav-item-->
					    {% endif %}
					    <li class="nav-item">
					        <!--//Bootstrap Icons: https://icons.getbootstrap.com/ -->
					        <a class="nav-link" href="{% url 'about_page' %}">
						        <span class="nav-icon">
						            <i class="fa fa-envelope fa-lg"></i>
						        </span>
		                        <span class="nav-link-text">About Ultranet</span>
					        </a><!--//nav-link-->
					    </li><!--//nav-item-->
					    <li class="nav-item">
					        <!--//Bootstrap Icons: https://icons.getbootstrap.com/ -->
					        <a class="nav-link" href="{% url 'legal_docs_page' %}">
						        <span class="nav-icon">
						            <i class="fa fa-file-invoice fa-lg"></i>
						        </span>
		                        <span class="nav-link-text">License</span>
					        </a><!--//nav-link-->
					    </li><!--//nav-item-->
				    </ul><!--//footer-menu-->
			    </nav>
		    </div><!--//app-sidepanel-footer-->
        </div><!--//sidepanel-inner-->
    </div><!--//app-sidepanel-->
</header><!--//app-header-->