Ultranet/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views


from account import views as account_views
from nomad import views as nomad_views
from blog.views import feed_view
from feedback import views as feedback_views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', nomad_views.HomeView.as_view(), name="home"),
    path('about/', nomad_views.AboutView.as_view(), name="about_page"),
    path('get_in_touch/', nomad_views.ContactView.as_view(), name="contact_page"),
    path('legal-docs/', nomad_views.LegalDocsView.as_view(), name="legal_docs_page"),

    path('register/', account_views.register_view, name="register"),
    path('login/', account_views.login_view, name="login"),
    path('logout/', account_views.logout_view, name="logout"),
    path('account/', include('account.urls', namespace="account")),
    path('friend/', include('friend.urls', namespace="friend")),
    path('', include('main_asgi.urls', namespace="main_asgi")),
    path('feedback/', include('feedback.urls', namespace="feedback")),
    path('notifications/', include('main_asgi.chat_urls', namespace="notifications")),
    path('blog/', include('blog.urls', namespace="blog")),
    path('', include('nomad.urls', namespace="nomad")),
    
    path('report/', feedback_views.create_report_view, name="report"),
    path('lobby/', feed_view, name="feed"),
    
    path('chat/', include('main_asgi.chat_urls', namespace="chat")),
    path('notifications/', include('main_asgi.notifications_urls', namespace="notification")),

    path('password-reset/', auth_views.PasswordResetView.as_view(template_name="account/password-reset/reset.html"), name="password_reset"),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='account/password-reset/reset_done.html'), name="password_reset_done"),
    path('password-reset/complete/', auth_views.PasswordResetCompleteView.as_view(template_name='account/password-reset/reset_complete.html'), name="password_reset_complete"),    
    path('password-reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="account/password-reset/reset_confirm.html"), name='password_reset_confirm'),

    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='account/password-reset/change_done.html'),name='password_change_done'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='account/password-reset/change.html'),name='password_change'),

    path('server_error/', nomad_views.server_error_view, name="500"),
    path('page_not_found/', nomad_views.page_not_found_view, name="404"),
    path('bad_request', nomad_views.bad_request_view, name="400"),
    path('permision_denied/', nomad_views.perm_denied_view, name="403"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = nomad_views.page_not_found_view
handler500 = nomad_views.server_error_view
handler403 = nomad_views.perm_denied_view
handler400 = nomad_views.bad_request_view

account/urls.py
from django.urls import path

from . import views

app_name="account"

urlpatterns = [
	path('redirect/', views.redirect_view, name="redirect"),
	path('update_profile/', views.update_profile_view, name="update_profile"),
	path('settings/<str:page>/', views.settings_view, name="settings"),
	path('details/<str:subject_username>/', views.details_view, name="details"),
	path('delete/', views.delete_account_view, name="delete"),
	path('<user_id>/edit/cropImage/', views.crop_image_view, name="crop_image"),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include


from . import views

from account import views as account_views

from .views import (
	# CRUD
	create_content_view,
	create_comment_view,

	update_content_view,
	update_comment_view,

	delete_content_view,
	delete_comment_view,

	feed_view,
	content_view,
	select_view,
	interact_view,
	)

app_name="blog"

urlpatterns = [

	path('create/<str:content_type>/', create_content_view, name="create_content"),
	path('<int:content_id>/', content_view, name="content"),
	path('poll/select/<int:value_id>/', select_view, name="select"),
	path('<int:content_id>/update/', update_content_view, name="update_content"),
	path('<int:content_id>/delete/', delete_content_view, name="delete_content"),

	path('<int:content_id>/<int:reply>/comments/create/', create_comment_view, name="create_comment"),
	path('content/<comment_id>/edit/', update_comment_view, name="update_comment"),
	path('content/<comment_id>/delete/', delete_comment_view, name="delete_comment"),

	path('interact/', interact_view, name="interact"),
]

blog/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField
from django.conf import settings
from django.utils import timezone
from django.db.models.signals import pre_save, post_save

import datetime

# Create your models here.

visibility_options = [
	('Anyone', 'Anyone'),
	('Friends', 'Friends'),
]

content_types = [
	('Post', 'Post'),
	('Poll', 'Poll'),
]


class Choice(models.Model):

	content		= models.ForeignKey('Content', on_delete=models.CASCADE, null=True)
	value 		= models.CharField(verbose_name="value", max_length=100, unique=False)
	votes  		= models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name="votes")
	timestamp 	= models.DateTimeField(verbose_name="timestamp", auto_now_add=True)
	
	
	def __str__(self):
		return self.value

	def add_vote(self, user):
		if not user in self.votes.all():
			self.votes.add(user)
			self.save()
		else:
			return False

	def remove_vote(self, user):
		if user in self.votes.all():
			self.votes.remove(user)
			self.save()
			return True
		else:
			return False

	def change_vote(self, user, value):

		if user in self.votes() and not user in value.votes():
			self.votes.remove_vote(user)
			value.add_vote(user)
			value.save()
			return True
		else:
			return False

	def clean_values(self, user):
		choices = self.content.choice_set.all()
		for choice in choices:
			if user in choice.votes.all():
				choice.remove_vote(user=user)

	@property
	def total_votes(self):
		vote_count=0
		for choice in self.content.choice_set.all():
			vote_count+=len(choice.votes.all())
		return vote_count
	


class ContentQuerySet(models.QuerySet):
    def search(self, query=None):
        if query is None or query == "":
            return self.none()
        lookups = Q(username__icontains=query)
        return self.filter(lookups) 

tag_choices = [
	"Operating Systems",
	"Competetive Programming",
	"Software",
	"Programming Languages",
	"Hardware",
]

class ContentManager(models.Manager):

	def create_content(self, author, text, content_type, draft, visibility, title, tags):
		if author==None:
			raise ValueError("Invalid author")
		if content_type!="Post" and content_type!="Poll":
			raise ValueError("Invalid content type")
		if len(tags)>=1:
			for tag in tags:
				if not tag in tag_choices:
					raise ValueError("Invalid tag")
				

		content = self.model(
				author=author,
				content_type=content_type,
				title=title,
				tags=tags,
				visibility=visibility,
				draft=draft,
		)
		if content_type=="Post" and len(text)>=3:
			content.text=text
			content.save(using=self._db)
			return content 
		elif content_type=="Poll":
			content.save(using=self._db)
			choices = text.replace('\r','').split('\n')
			if len(choices)<=1:
				raise ValueError("A poll must have 2 or more choices")
			content_text=""
			for choice in set(choices):
				poll_choice = Choice.objects.create(content=content, value=choice.lower().replace(' ','').replace('\r',''))
				poll_choice.save()
				content_text+='\n'+choice.lower()

			content.text=content_text[1:]
			content.save(using=self._db)
			return content

	def get_queryset(self):
		return ContentQuerySet(self.model, using=self._db)

	def search(self, query=None):
		return self.get_queryset().search(query=query)
		


class Content(models.Model):

	author 		= models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	title 		= models.CharField(verbose_name="title", max_length=70, null=True, blank=True, unique=False)
	content_type= models.CharField(choices=content_types, verbose_name="content_type", max_length=50, default="default")
	tags	 	= ArrayField(models.CharField(max_length=30, blank=True), size=5, blank=True)

	text  		= models.TextField(blank=True, null=True)

	comments 	= models.ManyToManyField('Comment', related_name="comments", blank=True)
	views 		= models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name="views")
	likes 		= models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name="likes")
	dislikes 	= models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name="dislikes")

	draft 		= models.BooleanField(verbose_name="draft", default=True)
	visibility 	= models.CharField(verbose_name="visibility", choices=visibility_options, default="Friends", max_length=100)

	timestamp 	= models.DateTimeField(verbose_name="timestamp", auto_now_add=True)	

	objects=ContentManager()

	def __str__(self):
		return self.content_type + ' | '

	def add_like(self, user):
		if user in self.dislikes.all():
			self.dislikes.remove(user)
			self.save()
			return True 
		else:
			if user in self.likes.all():
				return True
			self.likes.add(user)
			self.save()
			return True 
	
	def add_dislike(self, user):
		if user in self.likes.all():
			self.likes.remove(user)
			self.save()
			return True
		else:
			if user in self.dislikes.all():
				return True 
			self.dislikes.add(user)
			self.save()
			return True 

	def unlike(self, user):
		if user in self.likes.all(): 
			self.likes.remove(user)
			self.save()
			return True

	def undislike(self, user):
		if user in self.dislikes.all():
			self.dislikes.remove(user)
			self.save()
			return True

	@property
	def recent(self):
		now = timezone.now()
		return now - datetime.timedelta(days=14) <= self.pub_date <= now


class Comment(models.Model):

	author  		= models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	text 	 		= models.CharField(verbose_name="text", max_length=750, null=False, blank=True)
	content			= models.ForeignKey('Content', verbose_name="content", on_delete=models.CASCADE, blank=False, null=True)

	reply 			= models.ForeignKey('Comment', related_name="reply_obj", null=True, blank=True, on_delete=models.CASCADE)
	timestamp 		= models.DateTimeField(verbose_name="timestamp", auto_now_add=True)

	def __str__(self):
		return self.author.username

	def add_reply(self, comment):
		if not comment in self.replies.all():
			self.replies.add(comment)
			self.save()
			return True
		else:
			return False

blog/forms.py
from django import forms 
from .models import Choice, Comment, Content
from account.models import Account as BaseAccount





visibility_options_list = [
	'Friends',
	'Anyone',
]

visibility_options = [
	('Friends', 'Friends'),
	('Anyone', 'Anyone'),
]

types = [
	('Post', 'Post'),
	('Poll', 'Poll'),
	('Snippet', 'Snippet'),
]


class ContentCreationForm(forms.ModelForm):


	class Meta:
		model = Content
		fields = ('title', 'text', 'visibility', 'draft', 'tags')

	def clean(self):
		title = self.cleaned_data["title"]
		if title and len(title.replace(" ","")) <= 2:
			raise form.ValidationError("The title of your post is too small")

		visibility = self.cleaned_data["visibility"]
		if not visibility in visibility_options_list:
			raise forms.ValidationError("Please select a valid visibility option")

		draft = self.cleaned_data["draft"]
		if draft != True and draft != False:
			raise forms.ValidationError("Please check the draft checkbox or leave it unchecked")

		content_type = self.data["content_type"]
		if content_type!="Post" and content_type!="Poll":
			raise forms.ValidationError("Please do not alter the form or you will be banned from this platform")

		text = self.cleaned_data["text"]
		if content_type=="Post" and len(text.replace(' ','')) <= 2:
			raise forms.ValidationError("Your post content is too small")

		if content_type=="Poll" and len(text.replace('\r','').split('\n')) <= 1:
			raise forms.ValidationError("Poll choices should be 2 or more")

	def save(self, user, commit=True):
		content = Content.objects.create_content(
			author=user,
			text=self.cleaned_data["text"],
			content_type=self.data["content_type"],
			draft=self.cleaned_data["draft"],
			visibility=self.cleaned_data["visibility"],
			title=self.cleaned_data["title"],
			tags=[],
		)
		if commit:
			content.save()
		return content

class ContentUpdateForm(forms.ModelForm):

	class Meta:
		model = Content
		fields = ('title', 'text', 'visibility', 'draft', 'tags')

	def clean(self):
		title = self.cleaned_data["title"]
		if title and len(title.replace(" ","")) <= 2:
			raise form.ValidationError("The title of your post is too small")


		visibility = self.cleaned_data["visibility"]
		if not visibility in visibility_options_list:
			raise forms.ValidationError("Please select a valid visibility option")

		content_type = self.data["content_type"]
		if content_type!="Post" and content_type!="Poll":
			raise forms.ValidationError("Please do not alter the form or you will be banned from this platform")

		text = self.cleaned_data["text"]
		if content_type=="Post" and len(text.replace(' ','')) <= 2:
			raise forms.ValidationError("Your post content is too small")

		if content_type=="Poll" and len(text.replace('\r','').split('\n')) <= 1:
			raise forms.ValidationError("Poll choices should be 2 or more")


class CommentCreationForm(forms.ModelForm):

	class Meta:
		model = Comment
		fields = ('text',)

	def clean_text(self):
		text = self.cleaned_data['text']
		if len(text)<=2:
			# no need to be specifiv
			# once the form becomes invalid save() wont be invoked
			raise forms.ValidationError("---")
		return text

	def save(self, user, content, reply):
		comment = Comment.objects.create(
			author=user,
			text=self.cleaned_data['text'],
			content=content,
		)
		comment.save()
		if reply!=0:
			try:
				sub_comment = Comment.objects.get(id=reply)
				if sub_comment.content == content:
					comment.reply = sub_comment
				elif sub_comment.content != content:
					comment.delete()
					return None
			except:
				comment.delete()
				return None

		comment.save()
		return comment


class CommentUpdateForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ('text',)

	def clean_text(self):
		text = self.cleaned_data['text']
		if len(text)<=2:
			# no need to be specifiv
			# once the form becomes invalid save() wont be invoked
			raise forms.ValidationError("---")
		return text

	def save(self, comment):
		comment.text = self.cleaned_data['text']
		comment.save()
		return comment

blog/templates/blog/post/create.html
{% extends 'base.html' %}


{% block title %}
Create post
{% endblock title %}

{% block content %}

<div class="container-fluid">
	<div class="row justify-content-center">
		<div class="col-lg-7 col-md-10">
			<div class="rounded p-lg-5 p-2 shadow mt-5 align-middle">
				<form method="POST">
					{% csrf_token %}
					<div class="form-floating mb-3">
						<input type="text" name="title" class="form-control" maxlength="200" placeholder="Title" id="id_title">
						<label for="floatingInput">Title(optional)</label>
					</div>

					<p class="bold">Content:</p>
					<textarea name="text" cols="auto" rows="10" class="form-control mb-3" maxlength="5000" id="id_text"></textarea>

					<p class="text-dark bold">Category:</p>
					<select name="category" id="id_category" class="form-select mb-3">
					<option value="General">General</option>
					<option value="Software">Software</option>
					<option value="Hardware">Hardware</option>
					<option value="Linux">Linux</option>
					<option value="Windows">Windows</option>
					<option value="Programming / Coding">Programming / Coding</option>
					<option value="School">School</option>
					</select>

					<p class="text-dark bold">Visibility:</p>
					<select name="visibility" id="id_visibility" class="form-select mb-3">
					<option value="Friends">Friends</option>
					<option value="Public">Public</option>
					</select>

					<div class="form-group pb-4">
						<input type="checkbox" name="draft" id="id_draft" checked="">
						<label for="checkbox">Draft</label>
					</div>

					<p class="text-center"><button class="btn btn-primary btn-md btn-block-2" type="submit">Post</button></p>
				</form>
			</div>
		</div>
	</div>
</div>


{% endblock content %}

blog/templates/blog/post/details.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Post 
{% endblock title %}

{% block content %}

<style type="text/css">
	.bd-placeholder-img {
		font-size: 1.125rem;
		text-anchor: middle;
		-webkit-user-select: none;
		-moz-user-select: none;
		user-select: none;
	}

	@media (min-width: 768px) {
	.bd-placeholder-img-lg {
	font-size: 3.5rem;
		}
	}
	.image-container{
		max-width: 70px;
		height: auto;
	}
    .pp-image {
        width: 35px;
        height: 35px;
        margin: 7px 10px 7px 7px;
    }
    .ml-3 {
        margin-left: 12px;
    }
    .font-size-m {
        font-size: 25px;
    }
</style>

<div class="container-fluid" id="hanging-icons">
    <div class="row row-cols-1 row-cols-lg-1">
        <div class="col d-flex align-items-start">
            <div class="flex-grow-1 p-lg-2">
                <div class="row">
                    <div class="col-lg-7 col-md-12 col-sm-12 p-2">
                        <div class="shadow ">
                            {% if content.title %}
                            <p class="display-6 text-black">{{ content.title }}</p>
                            {% endif %}

                            

                            <div class="d-flex flex-nowrap flex-row">
                                <button type="button" class="flex-fill btn p-lg-2 p-sm-0 m-sm-0 pb-0 pt-0"><span><span class="material-icons" onclick="triggerLike({{ content.id }}, 'like', 'details')">thumb_up</span>&nbsp;{{ content.likes.all|length }}</span></button>
                                <button type="button" class="flex-fill btn p-lg-2 p-sm-0 m-sm-0 pb-0 pt-0"><span><span class="material-icons" onclick="triggerDisLike({{ content.id }}, 'dislike', 'details')">thumb_down</span>&nbsp;{{ content.dislikes.all|length }}</span></button>
                                <button type="button" class="flex-fill btn p-lg-2 p-sm-0 m-sm-0 pb-0 pt-0"><span class=""><span class="material-icons text-black">visibility </span>&nbsp;{{ content.views.all|length }}</span></button>
                                <button type="button" class="flex-fill btn p-lg-2 p-sm-0 m-sm-0 pb-0 pt-0"><span class="material-icons text-black">share</span></button>
                                {% if is_mine %}
                                <a href="{% url 'blog:update_post' post_id=post.id %}" class=""><button type="button" class="flex-fill btn p-lg-2 p-sm-0 m-sm-0 pb-0 pt-0"><span class="material-icons text-success">update</span></button></a>
                                <a href="{% url 'blog:delete_post' post_id=post.id %}" class=""><button type="button" class="flex-fill btn p-lg-2 p-sm-0 m-sm-0 pb-0 pt-0"><span><span class="material-icons text-danger">delete</span></span></a>
                            {% endif %} 
                            </div>
            
                            <div class="d-flex flex-row">
                                <div class="flex-grow-1">
                                    <a href="{% url 'account:details' subject_username=content.author.username %}" class="text-light font-weight-bold mb-0">
                                    {% if content.author.profile_image %}
                                    <img class="pp-image border border-dark rounded rounded-circle" src="{{ content.author.profile_image.url }}" alt="profile image" /><small>{% if content.author == request.user %}You{% else %}by {{ content.author }}{% endif %}</small></a>
                                    {% endif %}
                                    <small class="text-muted text-light tillium">{{ content.timestamp.date }}</small>
                                </div>
                                <div class="d-flex flex-shrink-1">
                                    <div class="icon-square bg-light text-dark ">
                                        <button class="btn border" type="button"><span class="material-icons">settings</span></button>
                                    
                                    </div>
                                </div>
                            </div>  
                        </div>
                        {% if cat_recoms or author_recoms %}
                            <div class="rounded shadow mt-4 bg-light p-2">
                                <div class="row">
                                    {% if cat_recoms %}
                                        <div class="col-lg-6 col-md-12 col-sm-12">
                                            <p class="h4 text-black">More like this</p>
                                            <div class="list-group">
                                                {% for recom in cat_recoms %}
                                                    <a href="#" class="list-group-item list-group-item-action"></a>
                                                {% endfor %}
                                            </div>
                                        </div>
                                    {% endif %}

                                    {% if author_recoms %}
                                        <div class="col-lg-6 col-md-12 col-sm-12">
                                            <p class="h4 text-black">More from the geek</p>
                                            <div class="list-group">
                                                {% for recom in author_recoms %}
                                                    <a href="#" class="list-group-item list-group-item-action">{{ recom }}</a>
                                                {% endfor %}
                                            </div>
                                        </div>
                                    {% endif %}
                                </div>
                            </div>
                        {% endif %}
                    </div>

                    <div class="col-lg-5 col-md-12 col-sm-12">
                        <div class="card border  shadow position-sticky" style="top: 6rem">
                            {% include 'blog/snippets/comments.html' %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

    </div> <!-- End of row-->
</div> <!-- End of container-->
{% include 'blog/snippets/like.html' %}
<script type="text/javascript">


    function report(reason) {
        var url = "{% url 'report' %}";

        payload = {
            "csrfmiddlewaretoken": "{{ csrf_token }}",
            "subject": "Post",
            "subject_id": {{ content.id }},
            "reason": reason,
        };
        $.ajax({
            type: 'POST',
            dataType: "json",
            url: url,
            timeout: 5000,
            data: payload,
            success: function(data) {
                console.log("SUCCESS")
            },
            error: function(data) {
                console.error("ERROR...")
            },
            complete: function(data){
                console.log(data)
                if (data.responseJSON.response == "Successful") {
                    alert("Report sent successfully , thank you for making Itranet a better place :)")
                }
                else if (data.responseJSON.response == "Inconsistent data") {
                    location = "{% url 'error' code=100 %}"
                }
                else if (data.responseJSON.response == "404") {
                    location = "{% url 'error' code=404 %}"
                }

            }
        });
    }


</script>

{% endblock content %}

blog/templates/blog/post/update.html
{% extends 'base.html' %}


{% block title %}
Update post
{% endblock title %}

{% block content %}

<div class="container-fluid">
	<div class="row justify-content-center">
		<div class="col-lg-7 col-md-10">
			<div class="rounded p-lg-5 p-2 shadow mt-4">
				<form method="POST">
					{% csrf_token %}
					<div class="form-floating mb-3">
						<input type="text" name="title" class="form-control" value="{{ post.content.title }}" maxlength="200" placeholder="Title" required="" id="id_title">
						<label for="floatingInput">Title</label>
					</div>

					<p class="bold">Content:</p>
					<textarea name="text" cols="auto" rows="10" class="form-control mb-3" maxlength="5000" id="id_text">{{ post.text }}</textarea>

					<p class="text-dark bold">Category:</p>
					<select name="category" id="id_category" class="form-select mb-3">
						<option value="{{ post.content.category }}">Current : {{ post.content.category }}</option>
						<option value="General">General</option>
						<option value="Software">Software</option>
						<option value="Hardware">Hardware</option>
						<option value="Linux">Linux</option>
						<option value="Windows">Windows</option>
						<option value="Programming / Coding">Programming / Coding</option>
						<option value="School">School</option>
					</select>

					<p class="text-dark bold">Visibility:</p>
					<select name="visibility" id="id_visibility" class="form-select mb-3">
						<option value="{{ post.content.visibility }}">Current : {{ post.content.visibility }}</option>
						<option value="Friends">Friends</option>
						<option value="Public">Public</option>
					</select>

					<div class="form-group pb-4">
						<input type="checkbox" name="draft" id="id_draft" {% if post.content.draft %}checked=""{% endif %}>
						<label for="checkbox">Draft</label>
					</div>

					<p class="text-center"><button class="btn btn-primary btn-md btn-block-2" type="submit">Save</button></p>
				</form>
			</div>
		</div>
	</div>
</div>


{% endblock content %}