Ultranet/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views


from account import views as account_views
from nomad import views as nomad_views
from blog.views import feed_view
from feedback import views as feedback_views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', nomad_views.HomeView.as_view(), name="home"),
    path('about/', nomad_views.AboutView.as_view(), name="about_page"),
    path('get_in_touch/', nomad_views.ContactView.as_view(), name="contact_page"),
    path('legal-docs/', nomad_views.LegalDocsView.as_view(), name="legal_docs_page"),

    path('register/', account_views.register_view, name="register"),
    path('login/', account_views.login_view, name="login"),
    path('logout/', account_views.logout_view, name="logout"),
    path('account/', include('account.urls', namespace="account")),
    path('friend/', include('friend.urls', namespace="friend")),
    path('', include('main_asgi.urls', namespace="main_asgi")),
    path('feedback/', include('feedback.urls', namespace="feedback")),
    path('notifications/', include('main_asgi.chat_urls', namespace="notifications")),
    path('blog/', include('blog.urls', namespace="blog")),
    path('', include('nomad.urls', namespace="nomad")),
    
    path('report/', feedback_views.create_report_view, name="report"),
    path('lobby/', feed_view, name="feed"),
    
    path('chat/', include('main_asgi.chat_urls', namespace="chat")),
    path('notifications/', include('main_asgi.notifications_urls', namespace="notification")),

    path('password-reset/', auth_views.PasswordResetView.as_view(template_name="account/password-reset/reset.html"), name="password_reset"),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='account/password-reset/reset_done.html'), name="password_reset_done"),
    path('password-reset/complete/', auth_views.PasswordResetCompleteView.as_view(template_name='account/password-reset/reset_complete.html'), name="password_reset_complete"),    
    path('password-reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="account/password-reset/reset_confirm.html"), name='password_reset_confirm'),

    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='account/password-reset/change_done.html'),name='password_change_done'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='account/password-reset/change.html'),name='password_change'),

    path('server_error/', nomad_views.server_error_view, name="500"),
    path('page_not_found/', nomad_views.page_not_found_view, name="404"),
    path('bad_request', nomad_views.bad_request_view, name="400"),
    path('permision_denied/', nomad_views.perm_denied_view, name="403"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = nomad_views.page_not_found_view
handler500 = nomad_views.server_error_view
handler403 = nomad_views.perm_denied_view
handler400 = nomad_views.bad_request_view

blog/urls.py
from django.contrib import admin
from django.urls import path, include


from . import views

from account import views as account_views

from .views import (
	# CRUD
	create_content_view,
	create_comment_view,

	update_content_view,
	update_comment_view,

	delete_content_view,
	delete_comment_view,

	feed_view,
	content_view,
	select_view,
	interact_view,
	)

app_name="blog"

urlpatterns = [

	path('create/<str:content_type>/', create_content_view, name="create_content"),
	path('<int:content_id>/', content_view, name="content"),
	path('poll/select/<int:value_id>/', select_view, name="select"),
	path('<int:content_id>/update/', update_content_view, name="update_content"),
	path('<int:content_id>/delete/', delete_content_view, name="delete_content"),

	path('<int:content_id>/<int:reply>/comments/create/', create_comment_view, name="create_comment"),
	path('content/<comment_id>/edit/', update_comment_view, name="update_comment"),
	path('content/<comment_id>/delete/', delete_comment_view, name="delete_comment"),

	path('interact/', interact_view, name="interact"),
]

nomad/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
app_name = "nomad";

urlpatterns = [

	path("dummy/", views.dummy_view),

]

nomad/models.py
from django.db import models

# Create your models here.

account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate
from django.utils import timezone 

import datetime
from .models import Account, AccountSettings, visibility_options_primary, visibility_options_secondary


class RegistrationForm(UserCreationForm):

	email = forms.EmailField(max_length=254, help_text='Add a valid email address.')

	class Meta:
		model = Account
		fields = (
			'accept',
			'email',
			'username',
			'name',
			'dob',
			'gender',
			'surname',
			'password1',
			'password2',
			)

	def clean_email(self):
		email = self.cleaned_data['email'].lower()
		accounts = Account.objects.filter(email=email)
		if len(accounts) >= 1:
			raise forms.ValidationError(f'Email {email} is already in use.')
		else:
			return email
		
	def clean_username(self):
		username = self.cleaned_data['username']
		accounts = Account.objects.filter(username=username)
		if len(accounts) >= 1:
			raise forms.ValidationError(f'Username {username} is already in use , try another one.')
		else:
			return username


	def clean_accept(self):
		accept = self.cleaned_data['accept']
		if not accept:
			raise forms.ValidationError('You must accept Ultranet\'s privacy policy and terms of use to continue')
		elif accept:
			return accept
	
class AuthenticationForm(forms.ModelForm):

	password = forms.CharField(label='Password', widget=forms.PasswordInput)

	class Meta:
		model = Account
		fields = ('email', 'password')

	def clean(self):
		email = self.cleaned_data['email']
		password = self.cleaned_data['password']
		try:
			account = Account.objects.get(email=email)
			auth_user_account = authenticate(email=email, password=password)
		except:
			raise forms.ValidationError("Invalid login")

class SettingsAccountForm(forms.ModelForm):

	class Meta:
		model = Account
		fields = (
			'email',
			'username',
			'name',
			'surname',
			'gender',
		)

	def clean_email(self):
		email = self.cleaned_data['email'].lower()
		accounts = Account.objects.filter(email=email)
		if len(accounts) > 1:
			return forms.ValidationError(f"Email {email} already in use")
		elif len(accounts) <= 1:
			return email
		else:
			raise forms.ValidationError("Invalid email")

	def clean_username(self):
		username = self.cleaned_data['username']
		accounts = Account.objects.filter(username=username)
		if len(accounts) > 1:
			return forms.ValidationError(f"Username {username} already in use")
		elif len(accounts) <= 1:
			return username
		else:
			raise forms.ValidationError("Invalid username")

	def clean_gender(self):
		gender = self.cleaned_data["gender"]
		if gender != 'Male' and gender != 'Female' and gender != 'Other':
			raise forms.ValidationError("Please select a valid gender")
		else:
			return gender

	def save(self, instance, commit=True):
		account = instance
		username = self.cleaned_data['username']
		email = self.cleaned_data['email']

		if email != account.email and len(Account.objects.filter(email=email))==1:
			raise forms.ValidationError("Email provided is already in use")

		if username != account.username and len(Account.objects.filter(username=username))==1:
			raise forms.ValidationError("Username provided is already in use")
		account.email = email
		account.username = username

		account.name = self.cleaned_data['name']
		account.surname = self.cleaned_data['surname']
		account.gender = self.cleaned_data['gender']
		if commit:
			account.save()
		return account

class SettingsPrivacyForm(forms.ModelForm):

	class Meta:
		model = AccountSettings
		fields = (
		'visibility_email',
		'visibility_personal_info',
		'visibility_bio',
		'visibility_social_links',
		'visibility_timeline',
		'visibility_friend_list',
		'visibility_dob',
		'visibility_gender',
		'friendship',
		'public_chat_perm',
		'private_chat_perm',
		)

	def save(self, instance, commit=True):
		settings = instance
		settings.visibility_email = self.cleaned_data['visibility_email']
		settings.visibility_personal_info = self.cleaned_data['visibility_personal_info']
		settings.visibility_bio = self.cleaned_data['visibility_bio']
		settings.visibility_social_links = self.cleaned_data['visibility_social_links']
		settings.visibility_timeline = self.cleaned_data['visibility_timeline']
		settings.visibility_friend_list = self.cleaned_data['visibility_friend_list']
		settings.visibility_gender = self.cleaned_data['visibility_gender']
		settings.visibility_dob = self.cleaned_data['visibility_dob']
		settings.friendship = self.cleaned_data['friendship']
		settings.private_chat_perm = self.cleaned_data['private_chat_perm']
		settings.public_chat_perm = self.cleaned_data['public_chat_perm']
		if commit:
			settings.save()
		return settings

class SettingsNotificationsForm(forms.ModelForm):

	class Meta:
		
		model = AccountSettings
		fields = (
			'like_notifications',
			'comment_notifications',
			'message_notifications',
			'friend_request_notifications',
			'push_notifications',
			'group_message_notifications',
		)
	
	def save(self, instance, commit=True):
		settings = instance
		settings.like_notifications = self.cleaned_data['like_notifications']
		settings.comment_notifications = self.cleaned_data['comment_notifications']
		settings.message_notifications = self.cleaned_data['message_notifications']
		settings.friend_request_notifications = self.cleaned_data['friend_request_notifications']
		settings.push_notifications = self.cleaned_data['push_notifications']
		settings.group_message_notifications = self.cleaned_data['group_message_notifications']

		if commit:
			settings.save()
		return settings

class UpdateProfileForm(forms.ModelForm):
	pass
	class Meta:
		model = Account
		fields = (
			'bio',
			'github',
			'stack',
			'youtube',
			'insta',
		)


	def save(self, instance, commit=True):
		account = instance
		account.bio = self.cleaned_data['bio']
		account.github = self.cleaned_data["github"]
		account.stack = self.cleaned_data["stack"]
		account.youtube = self.cleaned_data["youtube"]
		account.insta = self.cleaned_data["insta"]
		if commit:
			account.save()
		return account

class DeleteAccountForm(forms.Form):

	email = forms.EmailField()

	def clean_email(self):
		email = self.cleaned_data['email'].lower()
		try:
			account = Account.objects.get(email=email)
			return email
		except:
			raise forms.ValidationError("Invalid email")

	def save(self, instance, commit=True):
		instance.delete()

nomad/views.py
import random

from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.views import generic
from django.conf import settings

from account.models import Account
# from main_asgi.models import Notification, PrivateChatMessage, PrivateChatRoom
# from friend.utils import get_friend_request_or_false
# from blog.utils import get_content
# from feature.utils import get_resources

class HomeView(generic.TemplateView):
	template_name = "nomad/home.html"
	def get(self, request, *args, **kwargs):
		context = {}
		if request.user.is_authenticated:
			context = {}
			context["channel"] = get_object_or_404(Account, pk=request.user.id).channel_name
			context["con_general"] = True			
			context['welcome_msg'] = random.choice([
				'Welcome back ',
				'We\'ve missed you ',
				'Good to have you back ',
				'Now that you\'re back ',
				'Thanks for gracing us with your precense ',
				'Sup ',
			])
		return render(request, self.template_name, context)

class AboutView(generic.TemplateView):
	template_name = "nomad/about.html"
	def get(self, request, *args, **kwargs):
		context = {}
		if request.user.is_authenticated:
			context = {}
			context["con_general"] = True
			context["channel"] = get_object_or_404(Account, pk=request.user.id).channel_name
		return render(request, self.template_name, context)

class ContactView(generic.TemplateView):	
	template_name = "nomad/contact.html"
	def get(self, request, *args, **kwargs):
		context = {}
		context["whatsapp_link"] = settings.WHATSAPP_LINK
		context["telegram_link"] = settings.TELEGRAM_LINK
		context["phone_number"] = settings.PHONE_NUMBER
		context["email"] = settings.EMAIL_HOST
		context["physical_address"] = settings.PHYSICAL_ADDRESS
		if request.user.is_authenticated:
			context["con_general"] = True
			context["channel"] = get_object_or_404(Account, pk=request.user.id).channel_name
		return render(request, self.template_name, context)

class LegalDocsView(generic.TemplateView):
	template_name = "nomad/legal_docs.html"
	def get(self, request, *args, **kwargs):
		context = {}
		if request.user.is_authenticated:
			context = {}
			context["con_general"] = True
			context["channel"] = get_object_or_404(Account, pk=request.user.id).channel_name
		return render(request, self.template_name, context)

def page_not_found_view(request, *args, **kwargs):
	return render(request, "errors/404.html")	

def perm_denied_view(request, *args, **kwargs):
	return render(request, "errors/403.html")	

def server_error_view(request, *args, **kwargs):
	return render(request, "errors/500.html")	

def bad_request_view(request, *args, **kwargs):
	return render(request, "errors/400.html")	

def dummy_view(request, *args, **kwargs):
	return render(request, "dummies/bs5_profile_content.html")

nomad/templates/nomad/contact.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Get in touch
{% endblock title %}

{% block content %}



<div class="container-fluid">

    <header class="bg-light py-3 my-3">
      <div class="container px-5">
          <div class="row gx-5 align-items-center justify-content-center">
              <div class="col-lg-12 col-xl-12 col-xxl-12 rounded ">
                  <div class=" mt-1 text-center text-xl-start">
                      <h1 class="display-4 page-title fw-bolder tillium text-decoration-underline bold pt-2">Get in touch with us</h1>
                      <p class="lead fw-normal text-dark-50 mb-4">Quickly design and customize responsive mobile-first sites with Bootstrap, the world’s most popular front-end open source toolkit!</p>
                      <div class="d-grid gap-3 d-sm-flex justify-content-sm-center justify-content-xl-start">
                          
                          
                      </div>
                  </div>
              </div>
          </div>
      </div>
    </header>

  <!-- Team members section -->
    <section class="pb-5 bg-light">
        <div class="container px-5 mb-5">
            <div class="row justify-content-center">
                <div class="col-xxl-4 col-xl-4 col-lg-4 col-md-4 col-sm-12 col-xs-12 pb-5">
                    <div class="text-center">
                        <a class="text-primary px-2 me-sm-3" href="{{ whatsapp_link }}"><i class="fab fa-whatsapp fa-2x"></i></a><a class="text-info px-2 me-sm-3" href="{{ telegram_link }}"><i class="fab fa-telegram fa-2x"></i></a>
                        <h5 class="fw-bolder py-2">Chat with us</h5>
                        <div class="fw-bold noto-sans">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut consectetur</div>
                    </div>
                </div>
                <div class="col-xxl-4 col-xl-4 col-lg-4 col-md-4 col-sm-12 col-xs-12 pb-5">
                    <div class="text-center">
                        <a class="text-dark px-4 me-sm-3" href="{{ email }}"><i class="fa fa-envelope fa-2x"></i></span></a>
                        <h5 class="fw-bolder py-2">Email us</h5>
                        <div class="fw-bold noto-sans">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut consectetur</div>
                    </div>
                </div>
                <div class="col-xxl-4 col-xl-4 col-lg-4 col-md-4 col-sm-12 col-xs-12 pb-5">
                    <div class="text-center">
                        <p class="tillium fw-bold h4 border bg-dark rounded p-1 text-light">{{ phone_number }}</p>
                        <h5 class="fw-bolder py-2">Call us</h5>
                        <div class="fw-bold noto-sans">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut consectetur</div>
                    </div>
                </div>
            </div>
        </div>
    </section>

 
</div>

{% endblock content %}

nomad/templates/nomad/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
	{% if request.user.is_authenticated %}
		Welcome back {{ request.user.username }}
	{% else%}
		Welcome To Ultranet
	{% endif %}
{% endblock title %}

{% block content %}

<style type="text/css">
  .bd-placeholder-img {
    font-size: 1.125rem;
    text-anchor: middle;
    -webkit-user-select: none;
    -moz-user-select: none;
    user-select: none;
  }
  @media (min-width: 768px) {
  .bd-placeholder-img-lg {
  font-size: 3.5rem;
    }
  }
  .image-container, .logo-icon{
    max-width: 75px;
    height: auto;
  }

  .carousel {
  }
  /* Since positioning the image, we need to help out the caption */
  .carousel-caption {
	bottom: 3rem;
	z-index: 10;
  }
  
  /* Declare heights because of positioning of img element */
  .carousel-item {
	height: 19rem;
  }
  .carousel-item > img {
	position: absolute;
	top: 0;
	left: 0;
	min-width: 100%;
	height: 32rem;
  }
</style>

<div class="container-fluid">
  {% if request.user.is_authenticated %}
  <header class=" border-bottom py-5 my-3">
    <div class="container-fluid px-5 py-xl-5 my-xl-3 py-sm-3 my-sm-3 py-xs-2 my-xs-2">
      <div class="text-center">
        <h1 class="display-3 border-bottom border-top fw-bolder tillium">{{ welcome_msg }} {{ request.user.username }}</h1>
          <p class="lead mb-4">You have <a href="{% url 'notifications:home' %}"><span class="noti_count">0</span> new notification(s){{ noti_count|pluralize }} </a> and <a href="{% url 'chat:chats' %}"><span class="msg_count">0</span>new message(s)</a></p>
          <div class="d-grid d-sm-flex justify-content-sm-center">
            <a class="btn btn-primary btn-sm px-4 mx-2" href="{% url 'feed' %}">feed</a>
            <a class="btn btn-outline-primary btn-sm px-4 mx-2" href="{% url 'chat:chats' %}">chats</a>
          </div>
      </div>
    </div>
  </header>
  {% elif not request.user.is_authenticated %}
  	<header class="mt-3">
		<div class="container-fluid px-0 my-0">
			<div class="row gx-5 align-items-center justify-content-center">
				<div class="col-lg-12 col-xl-12 col-xxl-12 rounded ">
				  <div id="headerCarousel" class="carousel slide" data-bs-ride="carousel">
					  <div class="carousel-indicators">
						<button type="button" data-bs-target="#headerCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
						<button type="button" data-bs-target="#headerCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
						<button type="button" data-bs-target="#headerCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
					  </div>
					  <div class="carousel-inner">
						<div class="carousel-item active">
						  <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#777"/></svg>
				  
						  <div class="container">
							<div class="carousel-caption text-start">
							  <h1>Example headline.</h1>
							  <p>Some representative placeholder content for the first slide of the carousel.</p>
							  <p><a class="btn btn-lg btn-primary" href="#">Sign up today</a></p>
							</div>
						  </div>
						</div>
						<div class="carousel-item">
						  <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#777"/></svg>
				  
						  <div class="container">
							<div class="carousel-caption">
							  <h1>Another example headline.</h1>
							  <p>Some representative placeholder content for the second slide of the carousel.</p>
							  <p><a class="btn btn-lg btn-primary" href="#">Learn more</a></p>
							</div>
						  </div>
						</div>
						<div class="carousel-item">
						  <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#777"/></svg>
				  
						  <div class="container">
							<div class="carousel-caption text-end">
							  <h1>One more for good measure.</h1>
							  <p>Some representative placeholder content for the third slide of this carousel.</p>
							  <p><a class="btn btn-lg btn-primary" href="#">Browse gallery</a></p>
							</div>
						  </div>
						</div>
					  </div>
					  <button class="carousel-control-prev" type="button" data-bs-target="#headerCarousel" data-bs-slide="prev">
						<span class="carousel-control-prev-icon" aria-hidden="true"></span>
						<span class="visually-hidden">Previous</span>
					  </button>
					  <button class="carousel-control-next" type="button" data-bs-target="#headerCarousel" data-bs-slide="next">
						<span class="carousel-control-next-icon" aria-hidden="true"></span>
						<span class="visually-hidden">Next</span>
					  </button>
					</div>
				</div>
			</div>
		</div>
	</header>
    <div class="row g-0 justify-content-center">
	    <div class="col-12 col-lg-6 text-center p-5">
		    <div class="d-flex flex-column align-content-end">
			    <div class="">	
					<h2 class="text-center mt-3">Log in to Ultranet</h2>
				    <div class="mb-4"><img class="logo-icon me-2" src="{% static 'logos/light.svg' %}" alt="logo"></div>
					
			        <div class="text-start">
						<form class="login-form" action="{% url 'login' %}" method="post"> {% csrf_token %}        
							<div class="email mb-3">
								<label class="sr-only" for="signin-email">Email</label>
								<input placeholder="Email Address" class="form-control signin-email" type="email" name="email" required="" id="id_email">
							</div><!--//form-group-->
							<div class="password mb-3">
								<label class="sr-only" for="signin-password">Password</label>
								<input placeholder="Password" class="form-control signin-password" type="password" name="password" required="" id="id_password">	
								
								<div class="extra mt-3 row justify-content-between">
									<div class="col-6">
										<div class="form-check">
											<input class="form-check-input" type="checkbox" value="" id="RememberPassword" name="persistent">
											<label class="form-check-label" for="RememberPassword">
											Remember me
											</label>
										</div>
									</div><!--//col-6-->
									<div class="col-6">
										<div class="forgot-password text-end">
											<a href="{% url 'password_reset' %}">Forgot password?</a>
										</div>
									</div><!--//col-6-->
								</div><!--//extra-->
							</div><!--//form-group-->

							{% for field in form %}
							<p>
							{% for error in field.errors %}
							<p style="color: red">{{ error }}</p>
							{% endfor %}
							</p>
							{% endfor %}
							{% if form.non_field_errors %}
							<div style="color: red">
							<p>{{form.non_field_errors}}</p>
							</div>
							{% endif %}

							<div class="text-center">
								<button type="submit" class="btn btn-primary w-100 mx-auto">Log In</button>
							</div>
						</form>
						
						<div class="auth-option text-center pt-5">No Account? Sign up <a class="text-link" href="{% url 'register' %}" >here</a>.</div>
					</div><!--//auth-form-container-->	

			    </div><!--//auth-body-->
		    
		    </div><!--//flex-column-->   
	    </div><!--//auth-main-col-->

    </div><!--//row-->

  {% endif %}


</div>

{% endblock content %}